version: '3.8'
services:
  db:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - '5432:5432'
    volumes:
      - cereemdb:/var/lib/postgresql/data

volumes:
  cereemdb:

